version: '3.8'
services:
  haos:
    image: haos
    cap_add:
      - SYS_ADMIN
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    tmpfs:
      - /tmp
      - /run
      - /run/lock
      - /var/lib/journal
      - /var/log
      - /var/tmp
    stop_signal: SIGRTMIN+3
    tty: true
    stdin_open: true
    # Add read-only root filesystem and explicitly make certain paths writable
    read_only: true
    environment:
      - SYSTEMD_IGNORE_CHROOT=1
      - container=docker
