version: '3.8'
services:
  haos:
    image: haos
    privileged: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    tmpfs:
      - /tmp
      - /run
      - /run/lock
      - /var/lib/journal
      - /var/log
      - /var/tmp
      - /var/lib/private
      - /var/lib/systemd
      - /var/lib/dbus
      - /var/lib/machines
      - /var/lib/portables
      - /var/lib/hostname
      - /var/lib/udev
    stop_signal: SIGRTMIN+3
    tty: true
    stdin_open: true
    # Don't use read_only: true as it may be too restrictive
    # read_only: true
    environment:
      - SYSTEMD_IGNORE_CHROOT=1
      - container=docker
      - SYSTEMD_NSPAWN_API_VFS_WRITABLE=1
