version: '3.8'
services:
  haos:
    image: haos
    # privileged: true  # Commented out - replaced with granular options below
    cap_add:
      - ALL  # Grants all Linux capabilities (equivalent to privileged for capabilities)
    security_opt:
      - seccomp:unconfined  # Disables seccomp filtering (part of privileged mode)
      - apparmor:unconfined  # Disables AppArmor (if applicable)
    cgroup: host  # Share host's cgroup namespace - required for systemd
    tmpfs:
      - /run:rw,noexec,nosuid,size=100m  # Systemd runtime directory
      - /tmp:rw,noexec,nosuid,size=100m  # Temporary filesystem
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw  # Required for systemd containers
      - ./data:/mnt/data
      #- ./data_docker:/var/lib/docker
      - /var/run/docker.sock:/var/run/docker.sock  # Docker socket for supervisor
    stop_signal: SIGRTMIN+3
    tty: true
    stdin_open: true

