name: Docker Build

on:
  workflow_dispatch:
    inputs:
      release_tag:
        description: 'HAOS Release Tag'
        required: false
        default: 'latest'
        type: string
  # You can add other triggers like push or schedule if needed

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Run privileged build
      run: |
        docker run --rm --privileged \
          -v ${{ github.workspace }}:/workspace \
          -w /workspace \
          ubuntu:latest \
          bash -c "
            # Install necessary tools
            apt-get update
            apt-get install -y erofs-utils squashfs-tools curl rsync
            
            # Make scripts executable
            chmod +x build-haos-image.sh
            chmod +x extract-rootfs.sh
            
            # Run the build script with the release tag
            ./build-haos-image.sh ${{ github.event.inputs.release_tag }}
          "
          
    - name: Push to GitHub Packages
      # Add this step if you want to push the image to a registry
      # run: |
      #   echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      #   docker push ghcr.io/username/repository:tag
