name: Docker Build

on:
  workflow_dispatch:
    inputs:
      release_tag:
        description: 'HAOS Release Tag'
        required: false
        default: 'latest'
        type: string
  # You can add other triggers like push or schedule if needed

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v31
      with:
        nix_path: nixpkgs=channel:nixos-unstable   
        with:
          devShell: .#default # this is the default
    - name: Run privileged build
      run: sudo ./build-haos-image.sh ${{ github.event.inputs.release_tag }}

    # Add any post-build steps here if needed
    # For example, to push to a registry:
    # - name: Push to GitHub Packages
    #   if: success()
    #   run: |
    #     echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
    #     docker push ghcr.io/${{ github.repository }}:latest
